force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Duration_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_in_minutes__c</fullName>
    <label>Duration in minutes</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DoctorAppointmentHelper.cls
public class DoctorAppointmentHelper {

    public static Time convertStringToTime(String input) {
        // '15:35:00' -> ['15', '35', '00', '00']
        String[] inputSplit = input.split(':');
        Integer hour = Integer.valueOf(inputSplit[0]);
        Integer min = Integer.valueOf(inputSplit[1]);
        Integer sec = Integer.valueOf(inputSplit[2]);
        Integer ms = Integer.valueOf(inputSplit[3]);
        Time result = Time.newInstance(hour, min, sec, ms);
        return result;
    }

    public static List<SelectOption> generateSelectOptions(List<SObject> collection) {
        List<SelectOption> options = new List<SelectOption>();
        SelectOption blankOption = new SelectOption('', '');
        options.add(blankOption);
        for (SObject item : collection) {
            SelectOption option = new SelectOption((String)item.Id, (String)item.get('Name'));
            options.add(option);
        }
        return options;
    }

    public static Boolean hasDoctorsAppointments(Appointment__c inputAppointment, Integer startTime, Integer endTime) {
        List<Appointment__c> appointments = DoctorAppointmentsModel.getAppointments();
        for (Appointment__c record : appointments) {
            if ((inputAppointment.Doctor__c == record.Doctor__c)) {
                if (inputAppointment.Appointment_Date__c == record.Appointment_Date__c) {
                    return true;
                } else if (inputAppointment.Appointment_Date__c.date() == record.Appointment_Date__c.date()) {
                    Integer appointmentDate = record.Appointment_Date__c.hour() * 60 + record.Appointment_Date__c.minute();
                    Integer durationInMins = record.Duration_in_minutes__c.intValue();
                    if ((startTime > appointmentDate) && startTime < (appointmentDate + durationInMins)) {
                        return true;
                    } else if ((startTime < appointmentDate) && ((endTime) > appointmentDate)) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    public static Boolean hasDoctorAvailable(Appointment__c inputAppointment, Integer startTime, Integer endTime) {
        List<Doctor__c> doctors = DoctorAppointmentsModel.getDoctors();
        for (Doctor__c doctor : doctors) {
            Integer hoursStart = doctor.Working_Hours_Start__c.hour() * 60 + doctor.Working_Hours_Start__c.minute();
            Integer hoursEnd = doctor.Working_Hours_End__c.hour() * 60 + doctor.Working_Hours_End__c.minute();
            if (inputAppointment.Doctor__c == doctor.ID) {
                if ((startTime < hoursStart) || (startTime > hoursEnd)) {
                    return true;
                } else if (endTime > hoursEnd) {
                    return true;
                }
            }
        }
        return false;
    }

    public static void callAnaliticsService(String str) {
        // call to external HTTP service
        // HttpRequest h = new HttpRequest();
        // h.setBody('http://google.com');
        // h. to do some e
    }
}